### ISSUE TITLE
load model issue (about vision tower)

### ISSUE THREAD

**Issue by Eric-is-good** [CircleRadon/TokenPacker#10]
In sunshine-lwt/TokenPacker-7b-144token, use openai/clip-vit-large-patch14-336, when I load model, appear :
![image](https://github.com/user-attachments/assets/c2bcf2fe-5745-44c7-910a-2713cc7e4a53)
many weight can not use

**Comment by Eric-is-good** [comment]
![image](https://github.com/user-attachments/assets/fd561a8f-1fbd-41aa-a501-0bc3ce23cd8e)

**Comment by Eric-is-good** [comment]
![image](https://github.com/user-attachments/assets/c54fcfc6-efc6-448d-86e8-6785d310a2e3)

when i use the cli.py, what the diff with old llava cli

**Comment by LiWentomng** [comment]
@Eric-is-good 

Hello, the above information about loading model is normal. Regarding `cli.py`, we have not tested it yet and there are some missing. We will update it as soon as possible. You can try the pretrained models by benchmark evaluation, such as GQA.

**Comment by Eric-is-good** [comment]
@LiWentomng  Thank you !!!

**Comment by LiWentomng** [comment]
@Eric-is-good Hello, we have updated `cli.py`, please check it.
