### ISSUE TITLE
复现hd模型失败，

### ISSUE THREAD

**Issue by yangte3518880** [CircleRadon/TokenPacker#12]
我正在试图在mini-gemini的预训练和指令微调数据集上复现TokenPacker-HD-7b-9patch-144token，但是没能得到比较满意的结果。我得到的pretrain阶段的loss曲线如下
![image](https://github.com/user-attachments/assets/9ccb2333-ccb3-4edd-94c7-52b97c148d7c)
instruction tuning的loss曲线为
![image](https://github.com/user-attachments/assets/04e5c975-8179-48f7-9dfe-9fcd6c9a4eeb)
不知道能否开源一下你们的pretrain阶段loss曲线，方便对比。目前还不知道浮现的问题出现在哪里

**Comment by LiWentomng** [comment]
@yangte3518880 
你好，这是相应的pretrain阶段loss log文件
[trainer_state.json](https://github.com/user-attachments/files/16868895/trainer_state.json)
