### ISSUE TITLE
eval中用的jsonl来自哪里

### ISSUE THREAD

**Issue by Twi-etn** [CircleRadon/TokenPacker#17]
比如在下面的代码中的llava-tokenpacker-7b.jsonl文件来自哪里
`#!/bin/bash

SPLIT="mmbench_dev_20230712"

python -m llava.eval.model_vqa_mmbench \
    --model-path ./checkpoints/llava-tokenpacker \
    --question-file ./playground/data/eval/mmbench/$SPLIT.tsv \
    --answers-file ./playground/data/eval/mmbench/answers/$SPLIT/llava-tokenpacker-7b.jsonl \
    --single-pred-prompt \
    --temperature 0 \
    --conv-mode vicuna_v1

mkdir -p playground/data/eval/mmbench/answers_upload/$SPLIT

python scripts/convert_mmbench_for_submission.py \
    --annotation-file ./playground/data/eval/mmbench/$SPLIT.tsv \
    --result-dir ./playground/data/eval/mmbench/answers/$SPLIT \
    --upload-dir ./playground/data/eval/mmbench/answers_upload/$SPLIT \
    --experiment llava-tokenpacker-7b`

**Comment by CircleRadon** [comment]
@Twi-etn `llava-tokenpacker-7b.jsonl` 这个是推理输出的文件
