### ISSUE TITLE
report bugs

### ISSUE THREAD

**Issue by Gaffey** [CircleRadon/TokenPacker#3]
https://github.com/CircleRadon/TokenPacker/blob/305ce146ec8b6d8b5ec4959f6cac699e7c8b9ed4/llava/train/train.py#L320

There is a comment on Line 321 which makes the indented block wrong. Maybe there should be a comment on Line 320?

**Comment by Gaffey** [comment]
And there is no arguments in `train.py` named `down_rate`. Is that a bug?

**Comment by Gaffey** [comment]
https://github.com/CircleRadon/TokenPacker/blob/305ce146ec8b6d8b5ec4959f6cac699e7c8b9ed4/llava/model/multimodal_projector/builder.py#L54

Undefined name `grid`. Maybe it should be `raw_grid`?

**Comment by daixiangzi** [comment]
> https://github.com/CircleRadon/TokenPacker/blob/305ce146ec8b6d8b5ec4959f6cac699e7c8b9ed4/llava/model/multimodal_projector/builder.py#L54
> 
> Undefined name `grid`. Maybe it should be `raw_grid`?

yes,i also find the bug,i think grid is raw_grid

**Comment by CircleRadon** [comment]
@Gaffey @daixiangzi 
Sorry for mistakes, we have fixed it. Please try our latest code!
