### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by necrophagists** [CircleRadon/TokenPacker#5]
![image](https://github.com/CircleRadon/TokenPacker/assets/120618287/531c202e-7c6c-431d-9ca1-5b8560dec21d)
为什么这里要交换2 3 维度呢？

**Comment by LiWentomng** [comment]
@necrophagists 
这里交换是为了保持kernel size的顺序与h w一致。

**Comment by Eric-is-good** [comment]
@necrophagists 请问你代码跑起来了吗，我是指推理部分，cli.py，我有一些问题想请教
