### ISSUE TITLE
really like mini-gemini

### ISSUE THREAD

**Issue by Birdylx** [CircleRadon/TokenPacker#9]

**Comment by LiWentomng** [comment]
@Birdylx 
Thank you for your attention. We acknowledge  that  that our TokenPacker shares similar insights with the interaction module for dual-encoder in Mini-Gemini; however, our method diverge in details, particularly in the implementation. Besides, the motivations and framework of our work also differ from Mini-Gemini. Furthermore, our method achieved the better performance with a smaller token number compared to Mini-Gemini-HD.
